### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ShreyashPromact** [bluesliverx/savillians-gradle#5]
Hello,
I have include your library to publish app on Play Store from gradle. All configured proper i guess. But when i call command for publishing it "gradlew androidPublish", after some process it give me message with failure. Please check my below whole log for same:

D:\XYZ\ABCD>gradlew androidPublish
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes
:buildSrc:jar
:buildSrc:assemble
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify task execution graph listener.
> com.google.common.hash.HashCode.fromString(Ljava/lang/String;)Lcom/google/comm
on/hash/HashCode;
> com.google.common.hash.HashCode.fromString(Ljava/lang/String;)Lcom/google/comm
on/hash/HashCode;
> com.google.common.hash.HashCode.fromString(Ljava/lang/String;)Lcom/google/comm
on/hash/HashCode;
> com.google.common.hash.HashCode.fromString(Ljava/lang/String;)Lcom/google/comm
on/hash/HashCode;
> com.google.common.hash.HashCode.fromString(Ljava/lang/String;)Lcom/google/comm
on/hash/HashCode;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 30.683 secs

D:\XYZ\ABCD>

Please let me know if i am doing anything wrong.

**Comment by bluesliverx** [comment]
I would try adding the guava dependency explicitly to the classpath as explained in [this stackoverflow post](http://stackoverflow.com/questions/23413126/nosuchmethoderror-hashcode-fromstring-when-using-com-android-tools-buildgradle).  Let me know if that works/doesn't work.

**Comment by ShreyashPromact** [comment]
@bluesliverx  
After some try and error i got success with your library to publish app.

please keep updating your repository with the latest information.
You missed several things to mention in redme.md page for how to implement this with project.
Please update it with below required thing.

please add latest version of guava in to your dependency of the build Script.
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.savillians.gradle:android-publisher:0.4'
        classpath 'com.google.guava:guava:18.0'  // Must required...
    }
}

Also update to add latest version of your library.
The library version you have mention is: 0.1 while the latest one is 0.4

     classpath 'com.savillians.gradle:android-publisher:0.4'

The gradle command can be start with gradlew but you have mention it as gradle.

that should be like: gradlew androidPublish

So, as per my observation, that all things need to clarify in the redme.md file at below location:
https://github.com/bluesliverx/savillians-gradle/blob/master/android-publisher/README.md

Please update that all thing so that user can have proper information for how to implement your library and they can use same.


Thanks for reply and support.
Shreyash.

**Comment by bluesliverx** [comment]
Thanks for the feedback, I updated the readme.

**Comment by ShreyashPromact** [comment]
Hello @bluesliverx ,

I would like to suggest to add that readme information in below link:
https://github.com/bluesliverx/savillians-gradle/blob/master/README.md

Because mostly user go through with the initial readme file. You have mention all the things in the library readme file. Please add it to parent so that user can have proper information in first go.


Thanks.

Sincerely,
Shreyash

**Comment by bluesliverx** [comment]
@ShreyashPromact, I moved around the repository so that it is the only project in there.

**Comment by ShreyashPromact** [comment]
@bluesliverx That's sound good. Thank You. :)
